
START TRANSACTION;

SET @id := (SELECT `id` FROM `fields` WHERE `key` = "infoConfirmationDesc");
UPDATE `multi_lang` SET `content` = 'There are three type of auto-responders you can send to both the client and the admin. The first one is sent after new enquiry is submitted via the software. The second one is sent to confirm a successful payment and the third one after service has been canceled. You may enable or disable all auto-responders separately as well as customize the message using the tokens below.  <br/><br/><div class="float_left w200">{Title}<br/>{FirstName}<br/>{LastName}<br/>{Email}<br/>{Phone}<br/>{Notes}<br/>{Country}<br/>{City}<br/>{State}<br/>{Zip}<br/>{Address}<br/>{Company}<br/>{PaymentMethod}<br/>{CCType}<br/>{CCNum}<br/></div><div class="float_left w250">{Date}<br/>{ReturnDate}<br/>{From}<br/>{To}<br/>{Fleet}<br/>{Passengers}<br/>{Luggage}<br/>{UniqueID}<br/>{SubTotal}<br/>{Tax}<br/>{Total}<br/>{Deposit}<br/>{CCExp}<br/>{CCSec}<br/>{CancelURL}</div><div class="float_left w250">{ArrivalAirlineCompany}<br/>{ArrivalFlightNumber}<br/>{FlightArrivalTime}<br/>{DeptAirlineCompany}<br/>{DeptFlightNumber}<br/>{FlightDeptTime}<br/>{DestAddress}<br/>{CruiseShip}</div>' WHERE `foreign_id` = @id AND `model` = "pjField" AND `field` = "title";

SET @id := (SELECT `id` FROM `fields` WHERE `key` = "infoConfirmation2Desc");
UPDATE `multi_lang` SET `content` = 'There are three type of auto-responders you can send to both the client and the admin. The first one is sent after new enquiry is submitted via the software. The second one is sent to confirm a successful payment and the third one after service has been canceled. You may enable or disable all auto-responders separately as well as customize the message using the tokens below.  <br/><br/><div class="float_left w200">{Title}<br/>{FirstName}<br/>{LastName}<br/>{Email}<br/>{Phone}<br/>{Notes}<br/>{Country}<br/>{City}<br/>{State}<br/>{Zip}<br/>{Address}<br/>{Company}<br/>{PaymentMethod}<br/>{CCType}<br/>{CCNum}<br/></div><div class="float_left w250">{Date}<br/>{ReturnDate}<br/>{From}<br/>{To}<br/>{Fleet}<br/>{Passengers}<br/>{Luggage}<br/>{UniqueID}<br/>{SubTotal}<br/>{Tax}<br/>{Total}<br/>{Deposit}<br/>{CCExp}<br/>{CCSec}<br/>{CancelURL}</div><div class="float_left w250">{ArrivalAirlineCompany}<br/>{ArrivalFlightNumber}<br/>{FlightArrivalTime}<br/>{DeptAirlineCompany}<br/>{DeptFlightNumber}<br/>{FlightDeptTime}<br/>{DestAddress}<br/>{CruiseShip}</div>' WHERE `foreign_id` = @id AND `model` = "pjField" AND `field` = "title";

COMMIT;