
START TRANSACTION;

UPDATE `multi_lang` SET `content` = 'Your enquiry has been received. Details are below:\r\n\r\nPersonal details:\r\nTitle: {Title}\r\nFirst Name: {FirstName}\r\nLast Name: {LastName}\r\nE-Mail: {Email}\r\nPhone: {Phone}\r\nNotes: {Notes}\r\nCountry: {Country}\r\nCity: {City}\r\nState: {State}\r\nZip: {Zip}\r\nAddress: {Address}\r\nCompany: {Company}\r\n\r\nReservation details:\r\Date time: {DateTime}\r\nFrom: {From}\r\nTo: {To}\r\nFleet: {Fleet}\r\nPassengers: {Passengers}\r\nLuggage: {Luggage}\r\nUnique ID: {UniqueID}\r\nTotal: {Total}\r\n\r\nIf you want to cancel your reservation follow next link: {CancelURL}\r\n\r\nThank you, we will contact you ASAP.' WHERE `model` = "pjOption" AND `field` = "o_email_confirmation_message";

UPDATE `multi_lang` SET `content` = 'Payment has been received.\r\n\r\nPersonal details:\r\nTitle: {Title}\r\nFirst Name: {FirstName}\r\nLast Name: {LastName}\r\nE-Mail: {Email}\r\nPhone: {Phone}\r\nNotes: {Notes}\r\nCountry: {Country}\r\nCity: {City}\r\nState: {State}\r\nZip: {Zip}\r\nAddress: {Address}\r\nCompany: {Company}\r\n\r\nReservation details:\r\nDate time: {DateTime}\r\nFrom: {From}\r\nTo: {To}\r\nFleet: {Fleet}\r\nPassengers: {Passengers}\r\nLuggage: {Luggage}\r\nUnique ID: {UniqueID}\r\nTotal: {Total}\r\n\r\nIf you want to cancel your reservation follow next link: {CancelURL}\r\n\r\nThank you, we will contact you ASAP.' WHERE `model` = "pjOption" AND `field` = "o_email_payment_message";

UPDATE `multi_lang` SET `content` = 'You''ve just cancelled the service.\r\n\r\nPersonal details:\r\nTitle: {Title}\r\nFirst Name: {FirstName}\r\nLast Name: {LastName}\r\nE-Mail: {Email}\r\nPhone: {Phone}\r\nNotes: {Notes}\r\nCountry: {Country}\r\nCity: {City}\r\nState: {State}\r\nZip: {Zip}\r\nAddress: {Address}\r\nCompany: {Company}\r\n\r\nReservation details:\r\nDate time: {DateTime}\r\nFrom: {From}\r\nTo: {To}\r\nFleet: {Fleet}\r\nPassengers: {Passengers}\r\nLuggage: {Luggage}\r\nUnique ID: {UniqueID}\r\nTotal: {Total}\r\n\r\nIf you want to cancel your reservation follow next link: {CancelURL}\r\n\r\nThank you, we will contact you ASAP.' WHERE `model` = "pjOption" AND `field` = "o_email_cancel_message";

UPDATE `multi_lang` SET `content` = 'New enquiry has been received:\r\n\r\nPersonal details:\r\nTitle: {Title}\r\nFirst Name: {FirstName}\r\nLast Name: {LastName}\r\nE-Mail: {Email}\r\nPhone: {Phone}\r\nNotes: {Notes}\r\nCountry: {Country}\r\nCity: {City}\r\nState: {State}\r\nZip: {Zip}\r\nAddress: {Address}\r\nCompany: {Company}\r\n\r\nReservation details:\r\nDate time: {DateTime}\r\nFrom: {From}\r\nTo: {To}\r\nFleet: {Fleet}\r\nPassengers: {Passengers}\r\nLuggage: {Luggage}\r\nUnique ID: {UniqueID}\r\nTotal: {Total}\r\n\r\nIf you want to cancel your reservation follow next link: {CancelURL}\r\n\r\nThank you, we will contact you ASAP.' WHERE `model` = "pjOption" AND `field` = "o_admin_email_confirmation_message";

UPDATE `multi_lang` SET `content` = 'New payment has been made:\r\n\r\nPersonal details:\r\nTitle: {Title}\r\nFirst Name: {FirstName}\r\nLast Name: {LastName}\r\nE-Mail: {Email}\r\nPhone: {Phone}\r\nNotes: {Notes}\r\nCountry: {Country}\r\nCity: {City}\r\nState: {State}\r\nZip: {Zip}\r\nAddress: {Address}\r\nCompany: {Company}\r\n\r\nReservation details:\r\nDate time: {DateTime}\r\nFrom: {From}\r\nTo: {To}\r\nFleet: {Fleet}\r\nPassengers: {Passengers}\r\nLuggage: {Luggage}\r\nUnique ID: {UniqueID}\r\nTotal: {Total}\r\n\r\nIf you want to cancel your reservation follow next link: {CancelURL}\r\n\r\nThank you, we will contact you ASAP.' WHERE `model` = "pjOption" AND `field` = "o_admin_email_payment_message";

UPDATE `multi_lang` SET `content` = 'The following service has been canceled:\r\n\r\nPersonal details:\r\nTitle: {Title}\r\nFirst Name: {FirstName}\r\nLast Name: {LastName}\r\nE-Mail: {Email}\r\nPhone: {Phone}\r\nNotes: {Notes}\r\nCountry: {Country}\r\nCity: {City}\r\nState: {State}\r\nZip: {Zip}\r\nAddress: {Address}\r\nCompany: {Company}\r\n\r\nReservation details:\r\nDate time: {DateTime}\r\nFrom: {From}\r\nTo: {To}\r\nFleet: {Fleet}\r\nPassengers: {Passengers}\r\nLuggage: {Luggage}\r\nUnique ID: {UniqueID}\r\nTotal: {Total}\r\n\r\nIf you want to cancel your reservation follow next link: {CancelURL}\r\n\r\nThank you, we will contact you ASAP.' WHERE `model` = "pjOption" AND `field` = "o_admin_email_cancel_message";

COMMIT;