<?php
if (!defined("PJ_HOST")) define("PJ_HOST", "localhost");
if (!defined("PJ_USER")) define("PJ_USER", "root");
if (!defined("PJ_PASS")) define("PJ_PASS", "");
if (!defined("PJ_DB")) define("PJ_DB", "ahmet_oldbooking");
if (!defined("PJ_PREFIX")) define("PJ_PREFIX", "");
if (!defined("PJ_USE_IV")) define("PJ_USE_IV", "0");
if (!defined("PJ_INSTALL_FOLDER")) define("PJ_INSTALL_FOLDER", "/Ahmet/oldbooking/");
if (!defined("PJ_INSTALL_PATH")) define("PJ_INSTALL_PATH", "D:/PHP/PHP8.212/htdocs/Ahmet/oldbooking/");
if (!defined("PJ_INSTALL_URL")) define("PJ_INSTALL_URL", "http://localhost/Ahmet/oldbooking/");
if (!defined("PJ_SALT")) define("PJ_SALT", '2CK1I88B');
if (!defined("PJ_INSTALLATION")) define("PJ_INSTALLATION", "MTIyMjI1MjEwMjQ2NDM0NzgxMDU1MDg4NjgzNTgxNTA4NzM0MzQ1ODYzNDg0OTgyMDMwNTk0MDgxMzkwNTAxODk3NzYwMjUxNjIxNTQxMTM5MTk0ODU5MjczMTM3NTM2ODcwMSAyMzExNzA4NzM0MjAzMTEzNjM0NDEyMzAxODE4MjQ4NzI2MzIzNTY1MzA0Njc4Mzk1NDMzMjY5ODE0OTg2NDQ3MjQ4MjAyODIxNDYyOTk2Mzg2MTE3NTA3MTE0NTk0NjI0ODUgMTE2NTk1MzkxMjA4NzIzMzM1ODE0Mjc4MzY0NjEwMjU1NTk4MjUwMjQxNzgzMjgzOTk0OTY1NjgxNzQwNDIwNzYwNjcxNjAwODE2NjU4NzM3MDY2ODc1MjE3NzMyNTc5NzAwNiAxMjg0OTc2NDcwODg0OTU5NTY0Mjc5Nzk1NTgzMTMzODgxMDA4MTM4MjE5NjAxMDg3MjY2MTYxNzcwMDAyMjM3MzI2NjU4MTA0MDU5NTI5ODAzMzcyMDU4ODc5NDE4NzMxODY1IDEwNTk0MzM3NjA5OTAyNTU1NzM3MjY5NzkyMzc4Mzk2NjA5MDM0ODcwMzc1MzQxODU1MTE5NDg0OTA3NjUxNDIyNzgzOTQ2MzIyMTYxOTMxMTIxMTkyNDE3MTQxNzk3NDkwMCA2Nzc1MTM1OTg3ODQzNTcxNTQwNDQzNjEzMzE4Mjg5NjY1Nzc1NTIyNjc5Njk2NDgyNjAzMjE2MjEwODc5NDUzMjQ0ODM5NDQzNTc0NDc3NTIzNzM1MTU5OTI3MjMzMTI1NTUgMjQ5MjM0NTM2ODg1Nzk5ODA4ODQwNjEyMDM5MjAyODYwNjQ3MTA3MjI0NjM4MDQ5Njk5MTY0Mjk3NjExNDE1Njk3MzgwMzc3NTExMzI5NzUzNTU1NzQ0MDMxMDMwMTUxOTA4IDQzMjQzMzEzNDMxNDIxMzE4OTQ5ODIxODY4NjgwMDg3MzI1NjA1MzI0Njg4MTIyNzgxNjIzMzM2NTEyNjY5MzA4ODA4OTQyMTM4OTE1MTIwMTk0MzUyMTM4NTk1MTY3MDY4NSAxMzAwOTEyMTczMzEzMDM5Mjg3NzM1NTQ4NzUzNTg3NTUzNDQzODEzNTAyODk5ODU5OTUwNTY3ODU5MzIzOTQ1MDYxODM0NzM3MTMwNDg0MjcxMzgzMDE0MjQ2NzQ1MDkyNzUwIDE2MzUyMzczODkwMTc5MTU2MzkxNzE4MDY1ODQ1NDUyNTA5MjY4NTU2NDk3MjIyODQ5Nzk5NDMyNDgxODAzODQyODY2NjI5NDk4OTQwNjczNDI3NzIzNTYwMzE4Njg0MTEzMA==");
?>